version: '2'

services:
  drone-server:
    image: drone/drone:1
    container_name: drone-server
    ports:
      - 80:80
    volumes:
      - /var/lib/drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_SERVER_HOST="4789-123-193-82-121.jp.ngrok.io"
      - DRONE_SERVER_PROTO=http
      - DRONE_RPC_SECRET=db242daf100b137d40f7f40f82168b7b
      - DRONE_GITHUB_CLIENT_ID=0457dc2d0eff24b96947
      - DRONE_GITHUB_CLIENT_SECRET=9a6c06819584549103d8a3fc7d2c82771e38238c

  drone-runner:
    image: drone/drone-runner-docker:1
    container_name: drone-runner
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_SECRET=9a6c06819584549103d8a3fc7d2c82771e38238c
      - DRONE_RUNNER_CAPACITY=2